base: base_link
left_front:
  - lf_hip_1
  - lf_upper_1
  - lf_lower_1
  - lf_foot

right_front:
  - rf_hip_1
  - rf_upper_1
  - rf_lower_1
  - rf_foot

left_hind:
  - lh_hip_1
  - lh_upper_1
  - lh_lower_1
  - lh_foot

right_hind:
  - rh_hip_1
  - rh_upper_1
  - rh_lower_1
  - rh_foot